### ISSUE TITLE
Flycheck not reading packages

### ISSUE THREAD

**Issue by gopar** [mygnu/flycheck-vala.el#1]
Hey there, I'm new to emacs so the issue could be entirely my fault but I have installed the package and put a header comment at the top of the file such as 

```
// flycheck: valac --pkg gtk+-3.0  %f
```

For some reason even though I do that, I receive errors saying "namespace Gtk could not be found"

Any ideas or comments? By the way I think this package is pretty neat!

**Comment by mygnu** [comment]
I haven't been using or updating it for a while. I'll do a test run, what's your emacs version?

**Comment by gopar** [comment]
@mygnu Thanks. I'm on version 24.3.1
